image: koenhendriks/phpdocker:7.3

deploy_dot_com:
  stage: deploy
  environment:
    name: 'Deployment'
    url: https://koenhendriks.com
  only:
    - master
  before_script:
    - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
    - eval $(ssh-agent -s)
    - echo "$PRIVATE_KEY" | tr -d '\r' | ssh-add - > /dev/null
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
  script:
    - ssh koen@koenhendriks.com 'cd /home/koen/domains/koenhendriks.com/koenhendriks.com && git pull origin $CI_COMMIT_SHA && git checkout $CI_COMMIT_SHA'

deploy_dot_nl:
  stage: deploy
  environment:
    name: 'Deployment'
    url: http://koenhendriks.nl
  only:
    - master
  before_script:
    - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
    - eval $(ssh-agent -s)
    - echo "$PRIVATE_KEY" | tr -d '\r' | ssh-add - > /dev/null
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
  script:
    - ssh koen@koenhendriks.com 'cd /home/koen/domains/koenhendriks.nl/public_html && git pull origin $CI_COMMIT_SHA && git checkout $CI_COMMIT_SHA'

